---
name: Galaxy
on:
  push:
    branches:
      - main

jobs:
  galaxy:
    name: Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
